### ISSUE TITLE
Remove Version warning on stable

### ISSUE THREAD

**Issue by GaelVaroquaux** [skrub-data/skrub#1034]
### Describe the issue linked to the documentation

Current docs for stable have the version warning reserved for what are *not* the stable docs
![image](https://github.com/user-attachments/assets/629eeb42-f74e-4514-b5c8-d5fdfd9cce1b)

We need to remove that

### Suggest a potential alternative/fix

I think that the solution is to build the doc changing
https://github.com/skrub-data/skrub/blob/44c9a4d2ace06014630cc8abf392b85bf10bfa0a/doc/conf.py#L207
```python
        "version_match": "dev",
```
to stable

**Comment by jeromedockes** [comment]
the version match isn't a string to say which is the stable version but rather a sphinx variable indicating what is the version of the docs currently being built. So it does need to be changed but I think to something like `version` rather than `"stable"`

https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html#configure-switcher-version-match

however to be able to check we would need to fix the version.json first (I put 1.3 instead of 0.3): #1035

**Comment by GaelVaroquaux** [comment]
I think that it is the string used to match what's in the "version.json", so if we use "stable" in version.json, we can use "stable" in there too

**Comment by GaelVaroquaux** [comment]
Banner is gone:
https://skrub-data.org/stable/

Thanks!!
