### ISSUE TITLE
Font size in TableReport

### ISSUE THREAD

**Issue by GaelVaroquaux** [skrub-data/skrub#1037]
### Describe the bug

Fonts are too big in some environments (bigger than the fonts 
![image](https://github.com/user-attachments/assets/592cdf67-3128-4092-b61b-bb483b3678c1)

![image](https://github.com/user-attachments/assets/6a9616f5-e618-4d03-ba27-a7ce0d785e74)

### Steps/Code to Reproduce

Use it in vscode or check the render documentation

### Expected Results

The size of the font should be the same or smaller than the size of the code

### Actual Results

See figures above

### Versions

```shell
dev
```

**Comment by jeromedockes** [comment]
The sphinx documentation theme sets a smaller font size for preformatted text and code elements, that's why the code cell text is smaller. 

The skrub report uses the font size of the root element, that is the default chosen by the user agent or by the user in their configuration. (That is also the size of the non-code text and non-preformatted outputs in the documentation)

I think it might be a good idea to use the font size of the parent element instead (in this case the cell output), to allow the page containing the report to control its font size easily. however that wouldn't change the font in the sphinx gallery, because the default size of cell outputs is the current one.

we can also force a smaller font size in all cases, but then some users might have difficulty reading it

**Comment by jeromedockes** [comment]
I think it might be a question of the font itself rather than the font size because in the documentation the text in the report appears bigger than the main documentation text, even though it is set at the same size, because it is a different font

**Comment by jeromedockes** [comment]
I'll open open a pr to inherit the font & font-size when embedding the report.

Setting systematically a small font size is more up to debate IMO, let's first see how it looks after the first changes are done

**Comment by jeromedockes** [comment]
fixed in #1038
