### ISSUE TITLE
Code smell in the deduplication example

### ISSUE THREAD

**Issue by GaelVaroquaux** [skrub-data/skrub#466]
There are two things that worry me in the deduplication example and that suggest that we need to rework our API:
- The example uses compute_ngram_distance which is imported from a private submodule. We really should not import from private submodules in our examples, it teaches bad practice to our users and somewhat undoes the benefits of the private/public boundary which is to tell users what they can and cannot use safely.
  - Simple solution is probably to provide a public import for this function
- More fundamentally, I find that the example leaves a lot of non trivial pandas manipulation to the user. It feels that it might need a higher-level API or a bit more explanation. Maybe this will only be solved in a second step.

Ping @mjboos @jovan-stojanovic

**Comment by jovan-stojanovic** [comment]
I commented on #465, for the first point, we only need to import directly compute_ngram_distance.

**Comment by mjboos** [comment]
W.r.t. the first point: My bad, had made the method public but forgot to change it in the example.

W.r.t. the second point: Apart from wording in the example, I think this also relates to the discussion @jovan-stojanovic and I had in the PR. My most common use case for deduplication is creating a translation table (then refining it if duplicates are missed) to be used in a database `JOIN` instead of deduplicating directly - but we decided not to output such a translation table from the function at the moment. If this turns out to be a more general use case, it makes sense to adapt the API to support this workflow directly - which would make the example more concise as well.

**Comment by jovan-stojanovic** [comment]
> My most common use case for deduplication is creating a translation table (then refining it if duplicates are missed) to be used in a database `JOIN` instead of deduplicating directly - but we decided not to output such a translation table from the function at the moment. If this turns out to be a more general use case, it makes sense to adapt the API to support this workflow directly - which would make the example more concise as well.

I agree, maybe doing something similar to what the [`return_score` parameter does in the fuzzy_join](https://github.com/dirty-cat/dirty_cat/blob/main/dirty_cat/_fuzzy_join.py#L84)?

**Comment by mjboos** [comment]
That would require always returning a dataframe (with one or two columns based on whether it's a translation table or the deduplicated data), even if we just return the deduplicated data, right?
Question for me is whether it's worth to force the use of a dataframe as return (even when a list/array suffices in the default case) to support two different outputs (deduplicated data vs. translation table).

Alternative could be to have two different functions, one that deduplicates and another public function that creates a translation table instead, that do only a single thing.

Not sure what's better (depends on your guess what common workflows are, maybe we don't know yet either way), my intuition would be to use two functions, but no strong opinion.
